//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HW.LabStore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LabStoreEntities : DbContext
    {
        public LabStoreEntities()
            : base("name=LabStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_Admins> T_Admins { get; set; }
        public virtual DbSet<T_Buildings> T_Buildings { get; set; }
        public virtual DbSet<T_Labs> T_Labs { get; set; }
        public virtual DbSet<T_StoreCab> T_StoreCab { get; set; }
        public virtual DbSet<T_Students> T_Students { get; set; }
        public virtual DbSet<T_Teachers> T_Teachers { get; set; }
        public virtual DbSet<T_Topics> T_Topics { get; set; }
    }
}
