//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HW.LabStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Buildings
    {
        public string GUID { get; set; }
        public string BuildingName { get; set; }
        public string BuildingNum { get; set; }
        public string AreaGUID { get; set; }
        public string Position { get; set; }
        public string Responsibility { get; set; }
        public string ResponsibilityTel { get; set; }
    }
}
