//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HW.LabStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Students
    {
        public string GUID { get; set; }
        public string UserName { get; set; }
        public string UserPwd { get; set; }
        public string UserNum { get; set; }
        public string Grade { get; set; }
        public string Profession { get; set; }
        public string TopicID { get; set; }
        public string LabGUID { get; set; }
        public string DepartGUID { get; set; }
    }
}
