//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HW.LabStore.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPMS_TBL_Budget_IntermediateResult
    {
        public int CalcId { get; set; }
        public int ProjectId { get; set; }
        public int ProjectBudgetId { get; set; }
        public decimal PTDRevenue { get; set; }
        public decimal PTDCost { get; set; }
        public decimal PTDMargin { get; set; }
        public decimal PTDMarginPrecent { get; set; }
        public Nullable<decimal> FirstRevenue { get; set; }
        public Nullable<decimal> FirstCost { get; set; }
        public Nullable<decimal> FirstMargin { get; set; }
        public Nullable<decimal> FirstMarginPrecent { get; set; }
        public Nullable<decimal> RevisedRevenue { get; set; }
        public Nullable<decimal> RevisedCost { get; set; }
        public Nullable<decimal> RevisedMargin { get; set; }
        public Nullable<decimal> RevisedMarginPrecent { get; set; }
        public decimal ProposedRevenue { get; set; }
        public decimal ProposedCost { get; set; }
        public decimal ProposedMargin { get; set; }
        public decimal PropsoedMarginPrecent { get; set; }
        public decimal VarianceRevenue { get; set; }
        public decimal VarianceCost { get; set; }
        public decimal VarianceMargin { get; set; }
        public decimal VarianceMarginPrecent { get; set; }
        public decimal NetRevenue { get; set; }
        public decimal NetCost { get; set; }
        public decimal NetMargin { get; set; }
        public decimal NetMarginPrecent { get; set; }
        public Nullable<decimal> CostSheetRevenue { get; set; }
        public Nullable<decimal> CostSheetCost { get; set; }
        public Nullable<decimal> CostSheetMargin { get; set; }
        public Nullable<decimal> CostSheetMarginPrecent { get; set; }
        public decimal MarginErosion { get; set; }
        public int VersionNo { get; set; }
        public int RevisedNo { get; set; }
        public bool IsEProject { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public string TransactionId { get; set; }
    }
}
