//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HW.LabStore.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPMS_TBL_Approval_Condition_Setup
    {
        public IPMS_TBL_Approval_Condition_Setup()
        {
            this.IPMS_TBL_Approval_Action_Setup = new HashSet<IPMS_TBL_Approval_Action_Setup>();
        }
    
        public int ConditionId { get; set; }
        public string Description { get; set; }
        public string Condition { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int LastUpdatedBy { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public string TransactionId { get; set; }
    
        public virtual ICollection<IPMS_TBL_Approval_Action_Setup> IPMS_TBL_Approval_Action_Setup { get; set; }
    }
}
