//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HW.LabStore.DbModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mallStoreEntities : DbContext
    {
        public mallStoreEntities()
            : base("name=mallStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<IPMS_TBL_Approval_Action_Setup> IPMS_TBL_Approval_Action_Setup { get; set; }
        public DbSet<IPMS_TBL_Approval_Condition_Setup> IPMS_TBL_Approval_Condition_Setup { get; set; }
        public DbSet<IPMS_TBL_Approval_Setup> IPMS_TBL_Approval_Setup { get; set; }
        public DbSet<IPMS_TBL_Approval_User> IPMS_TBL_Approval_User { get; set; }
        public DbSet<IPMS_TBL_Budget_IntermediateResult> IPMS_TBL_Budget_IntermediateResult { get; set; }
        public DbSet<IPMS_TBL_Approval_Flow> IPMS_TBL_Approval_Flow { get; set; }
    }
}
